[package]
name = "luaegui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
derive_more = { version = "*", default-features = false, features = [
    "from",
    "deref",
    "deref_mut",
    "from",
    "as_ref",
    "as_mut",
] }
egui = "0.18.1"
tealr = { version = "*", path = "../tealr", features = [
    "mlua_luajit",
    "derive",
], default-features = false }

[dev-dependencies]
eframe = "0.18.0"
serde_json = "*"
