[package]
name = "luaegui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["lua"]
lua = ["dep:tealr"]

[dependencies]
egui = "0.18.1"
tealr = {version =  "*", git = "https://github.com/lenscas/tealr.git", features = ["mlua_luajit", "derive"], default-features = false, optional = true}
thiserror = "1.0.31"
[dev-dependencies]
eframe = "0.18.0"