[package]
name = "luaegui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
egui = "0.21.0"
mlua = { git = "https://github.com/khvzak/mlua.git", features = ["luau"] }
