name: Github Pages

on: [push]

permissions:
  contents: write

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # repo checkout
      - uses: mymindstorm/setup-emsdk@v13 # setup emscripten toolchain
        with:
          version: 3.1.52
      - uses: actions-rs/toolchain@v1 # get rust toolchain for wasm
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten
          override: true
      - name: Check Emscripten # just to make sure that emscripten is properly installed
        run: emcc -v
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v1
      - name: Build # bash script to build and put all required files inside a directory called "dist"
        run: ./build_web.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist