name: Deploy Github Pages
on: [push]
permissions:
  contents: write
jobs:
  github-pages:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      
      - name: Install Lua/LuaJIT 
        uses: leafo/gh-actions-lua@v9.1.0
        with:  
          luaVersion: "luajit-openresty"       
      
      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4
        
      - name: Install teal
        run: sudo luarocks install tl

      - name: Install tealr_docgen
        run: cargo install --git https://github.com/lenscas/tealr_doc_gen

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: cargo run --example=docgen

      - name: Generate Docs
        run: mkdir pages && generate_docs --json luaeguidocs.json --name "luaegui" --build_folder "pages" --root "egui"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages