name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  github-pages:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      
      - name: Install luajit
        run: sudo apt install luajit libluajit-5.1-dev

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: cargo run --example=docgen

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: luadocs_egui